name = "druggedapp-landing"
compatibility_date = "2024-04-10"
pages_build_output_dir = "dist"

[env.production]
# Add aggressive caching for static assets
[[routes]]
pattern = "/assets/*"
headers = { Cache-Control = "public, max-age=31536000, immutable" }
